###
# @name principalUser
GET {{host}}/api/principal HTTP/1.1
Authorization: Basic user 12345678
###
# @name principalOldUser
GET {{host}}/api/principal HTTP/1.1
Authorization: Basic old_user abcd1234
###
# @name authenticationUser
GET {{host}}/api/authentication HTTP/1.1
Authorization: Basic user 12345678
###
# @name authenticationOldUser
GET {{host}}/api/authentication HTTP/1.1
Authorization: Basic old_user abcd1234
###
GET {{host}}/authorize/anonymous HTTP/1.1
