server:
    port: 8080
    servlet:
        context-path: /
spring:
    application:
        name: security-springboot
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/user_db?serverTimezone=UTC
        username: root

    thymeleaf:
        prefix: classpath:/statics/
    suffix=: html

